"""Exact hardware catalog for the standalone cost model."""

from __future__ import annotations

from ..model import HardwareSpecRef
from .b200 import (
    B200_CALIBRATION_ID,
    B200_CUDA_CORE,
    B200_GMEM_READ,
    B200_GMEM_WRITE,
    B200_HARDWARE_ID,
    B200_MBARRIER_SLOTS,
    B200_REGISTERS_32BIT,
    B200_RF_READ,
    B200_RF_WRITE,
    B200_SCHEMA_VERSION,
    B200_SMEM_BYTES,
    B200_SMEM_READ,
    B200_SMEM_WRITE,
    B200_STATIC_RESOURCE_IDS,
    B200_TEMPORAL_RESOURCE_IDS,
    B200_TENSOR_CORE,
    B200_TENSOR_INFLIGHT,
    B200_TMA,
    B200_TMA_INFLIGHT,
    B200_TMEM_BYTES,
    B200_TMEM_READ,
    B200_TMEM_WRITE,
    B200_WARP_ISSUE,
    B200_WARPS,
    b200_hardware_spec,
)
from .model import (
    FactOrigin,
    FactProvenance,
    HardwareSpec,
    StaticResourceSpec,
    StaticUnit,
    TemporalResourceSpec,
)
from .registry import HardwareCatalog, b200_hardware_catalog

__all__ = [
    "B200_CALIBRATION_ID",
    "B200_CUDA_CORE",
    "B200_GMEM_READ",
    "B200_GMEM_WRITE",
    "B200_HARDWARE_ID",
    "B200_MBARRIER_SLOTS",
    "B200_REGISTERS_32BIT",
    "B200_RF_READ",
    "B200_RF_WRITE",
    "B200_SMEM_BYTES",
    "B200_SMEM_READ",
    "B200_SMEM_WRITE",
    "B200_SCHEMA_VERSION",
    "B200_STATIC_RESOURCE_IDS",
    "B200_TENSOR_CORE",
    "B200_TENSOR_INFLIGHT",
    "B200_TMA",
    "B200_TMA_INFLIGHT",
    "B200_TMEM_BYTES",
    "B200_TMEM_READ",
    "B200_TMEM_WRITE",
    "B200_TEMPORAL_RESOURCE_IDS",
    "B200_WARPS",
    "B200_WARP_ISSUE",
    "FactOrigin",
    "FactProvenance",
    "HardwareCatalog",
    "HardwareSpec",
    "HardwareSpecRef",
    "StaticResourceSpec",
    "StaticUnit",
    "TemporalResourceSpec",
    "b200_hardware_catalog",
    "b200_hardware_spec",
]
